/*
 * This source file was generated by the Gradle 'init' task
 */
package labor.learn

import java.nio.charset.StandardCharsets.UTF_8
import java.util.Scanner

fun main() {
    val scanner = Scanner(System.`in`, UTF_8.name())
}
