/*
 * This source file was generated by the Gradle 'init' task
 */
package labor.learn

class Atm {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(Atm().greeting)
}
